name: ditonton
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.3.9"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.7
  about:
    path: about
  core:
    path: core
  search:
    path: search
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  flutter_gen: ^5.1.0+1

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - certificate/
