// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpzDgJ7iHw-BXHeNLQbW-V7McJyfwUiOo',
    appId: '1:463754159915:android:fd48d6734b492886bec76e',
    messagingSenderId: '463754159915',
    projectId: 'apps-movie-tv-ditonton',
    databaseURL: 'https://apps-movie-tv-ditonton-default-rtdb.firebaseio.com',
    storageBucket: 'apps-movie-tv-ditonton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuG0l1WVqQde9GcaeURWKRHz8WGdZARs0',
    appId: '1:463754159915:ios:ec3e84d47bef3efabec76e',
    messagingSenderId: '463754159915',
    projectId: 'apps-movie-tv-ditonton',
    databaseURL: 'https://apps-movie-tv-ditonton-default-rtdb.firebaseio.com',
    storageBucket: 'apps-movie-tv-ditonton.appspot.com',
    iosClientId: '463754159915-ugulba5ud36no21fp9a5eomh80vldo7a.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
